import { ScrapPriceInfo, RecyclerFacility, SaleHistoryItem, RepairHistoryItem, DIYProject, AgentAnalysisResult } from '../types';

export const SCRAP_PRICES: ScrapPriceInfo[] = [
  {
    id: 'cables',
    key: 'cables',
    name: 'Long Copper Cables & Armored Wire',
    nameHi: 'लंबे तांबे के केबल और तार',
    nameMr: 'लांब तांब्याच्या तारा आणि केबल',
    currentRate: 520,
    unit: '₹ / kg',
    change24h: 3.8,
    trend: 'up',
    high7d: 535,
    low7d: 495,
    marketSource: 'MCX Copper Spot & Pune Mandi',
    purityGrade: 'Grade-1 Heavy Bright (98%+ Cu)',
    description: 'Armored industrial and household power cables with clean copper recovery core.',
    sparkline: [495, 502, 508, 514, 520],
    threeDType: 'cables',
  },
  {
    id: 'tv',
    key: 'tv',
    name: 'Old CRT & LED Televisions',
    nameHi: 'पुराने टीवी (CRT / LED)',
    nameMr: 'जुने टीव्ही (CRT / LED)',
    currentRate: 85,
    unit: '₹ / unit-kg eq.',
    change24h: 1.2,
    trend: 'up',
    high7d: 90,
    low7d: 78,
    marketSource: 'CPCB E-Waste Authorized Rate Board',
    purityGrade: 'Copper Deflection Yoke + Lead-Glass Chassis',
    description: 'Cathode ray tubes contain high-value deflection copper yokes and power transformer coils.',
    sparkline: [78, 80, 81, 83, 85],
    threeDType: 'tv',
  },
  {
    id: 'dishtv',
    key: 'dishtv',
    name: 'DishTV Satellite Antenna & Coaxial Set',
    nameHi: 'डिश टीवी एंटीना और सेटअप बॉक्स',
    nameMr: 'डिश टीव्ही अँटेना आणि सेट-अप बॉक्स',
    currentRate: 62,
    unit: '₹ / kg',
    change24h: 0.5,
    trend: 'stable',
    high7d: 65,
    low7d: 60,
    marketSource: 'Maharashtra Scrap Metal Index',
    purityGrade: 'Galvanized Sheet Steel + Aluminum LNB Bracket',
    description: 'DTH parabolic reflector dishes, brass F-connectors, and copper shield cables.',
    sparkline: [60, 61, 62, 61, 62],
    threeDType: 'dishtv',
  },
  {
    id: 'phone',
    key: 'phone',
    name: 'Old Mobile Phones (Repair/Scrap)',
    nameHi: 'पुराने मोबाइल फोन (मरम्मत/कबाड़)',
    nameMr: 'जुने मोबाईल फोन (दुरुस्ती/भंगार)',
    currentRate: 350,
    unit: '₹ / device base',
    change24h: 5.4,
    trend: 'up',
    high7d: 380,
    low7d: 320,
    marketSource: 'Refurbish Tech Exchange & Gold Recovery',
    purityGrade: 'Gold/Palladium contacts or Direct Component Re-use',
    description: 'Higher value when sent for screen/battery refurbishing (+₹1,500+) versus raw crushing.',
    sparkline: [320, 335, 340, 345, 350],
    threeDType: 'phone',
  },
  {
    id: 'pcb',
    key: 'pcb',
    name: 'Motherboard & High-Grade PCBs',
    nameHi: 'कंप्यूटर मदरबोर्ड और ग्रीन सर्किट',
    nameMr: 'मदरबोर्ड आणि कॉम्प्युटर सर्किट',
    currentRate: 185,
    unit: '₹ / kg',
    change24h: 2.1,
    trend: 'up',
    high7d: 190,
    low7d: 175,
    marketSource: 'National Precious Metals Recycling Index',
    purityGrade: 'Gold Finger Pin Connector Class-A',
    description: 'PCBs from servers and laptops contain gold, silver, palladium and high-grade copper.',
    sparkline: [175, 178, 180, 182, 185],
    threeDType: 'pcb',
  },
  {
    id: 'motor',
    key: 'motor',
    name: 'Electric Motors & Alternator Coils',
    nameHi: 'इलेक्ट्रिक मोटर और तांबा कॉइल',
    nameMr: 'इलेक्ट्रिक मोटार आणि तांब्याची कॉइल',
    currentRate: 240,
    unit: '₹ / kg',
    change24h: -1.0,
    trend: 'down',
    high7d: 250,
    low7d: 235,
    marketSource: 'Pune Industrial Heavy Metal Board',
    purityGrade: 'Silicon Stator + 85% Enamelled Copper',
    description: 'Pumps, ceiling fans, and industrial induction motors with dense copper windings.',
    sparkline: [250, 248, 245, 242, 240],
    threeDType: 'motor',
  },
  {
    id: 'battery',
    key: 'battery',
    name: 'Lead-Acid & Lithium-Ion Batteries',
    nameHi: 'लेड-एसिड और लिथियम बैटरी',
    nameMr: 'बॅटरी (लेड ऍसिड आणि लिथियम)',
    currentRate: 110,
    unit: '₹ / kg',
    change24h: 1.5,
    trend: 'up',
    high7d: 115,
    low7d: 104,
    marketSource: 'CPCB Battery Waste Management Registry',
    purityGrade: 'Strict Authorized Hazardous Facility Only',
    description: 'Inverter batteries and e-bike packs. Handover strictly to CPCB authorized smelters.',
    sparkline: [104, 106, 108, 109, 110],
    threeDType: 'battery',
  },
  {
    id: 'plastic',
    key: 'plastic',
    name: 'PET Bottles & Rigid HDPE Plastics',
    nameHi: 'प्लास्टिक की बोतलें और कंटेनर',
    nameMr: 'प्लास्टिकच्या बाटल्या आणि कॅन',
    currentRate: 34,
    unit: '₹ / kg',
    change24h: 0.0,
    trend: 'stable',
    high7d: 36,
    low7d: 32,
    marketSource: 'Plastic Circular Alliance Maharashtra',
    purityGrade: 'Clear Granulate Flake Grade',
    description: 'High recyclability. Also prime material for CreateOwn DIY gardening and recrafting.',
    sparkline: [32, 33, 34, 34, 34],
    threeDType: 'plastic',
  },
];

export const AUTHORIZED_RECYCLERS: RecyclerFacility[] = [
  {
    id: 'rec-1',
    name: 'GreenTech Circular Refineries Pvt Ltd',
    cpcbRegistrationNo: 'CPCB/EW-REG/MH/2024/0981',
    location: 'Bhosari MIDC Industrial Zone',
    city: 'Pune, Maharashtra',
    distanceKm: 4.8,
    reliabilityScore: 98,
    verified: true,
    phone: '+91 98231 44521',
    materialsAccepted: ['Cables & Wires', 'CRT & LED TVs', 'PCBs & Motherboards', 'Electric Motors'],
    pickupAvailable: true,
    minWeightKg: 10,
    specialOfferRate: '+₹15/kg bonus on clean copper cables above 25kg',
    operatingHours: '08:00 AM – 07:30 PM',
  },
  {
    id: 'rec-2',
    name: 'EcoDismantle Authorized Hub',
    cpcbRegistrationNo: 'CPCB/EW-REG/MH/2023/0412',
    location: 'Chakan Automotive E-Waste Park',
    city: 'Pune, Maharashtra',
    distanceKm: 9.2,
    reliabilityScore: 95,
    verified: true,
    phone: '+91 94220 89311',
    materialsAccepted: ['DishTV Antennas', 'CRT TVs', 'Transformers', 'Industrial Scrap'],
    pickupAvailable: true,
    minWeightKg: 20,
    specialOfferRate: 'Free weighbridge weighing + instant UPI payout',
    operatingHours: '07:00 AM – 08:00 PM',
  },
  {
    id: 'rec-3',
    name: 'E-Parisaraa Precious Recovery Facility',
    cpcbRegistrationNo: 'CPCB/EW-REG/KA/2021/0088',
    location: 'Hadapsar Electronic Cluster',
    city: 'Pune & Bengaluru Corridor',
    distanceKm: 12.5,
    reliabilityScore: 96,
    verified: true,
    phone: '+91 80278 12399',
    materialsAccepted: ['PCBs', 'Old Mobile Phones', 'Server Cards', 'Li-Ion Batteries'],
    pickupAvailable: false,
    minWeightKg: 5,
    specialOfferRate: 'Top gold-finger recovery payout with zero middleman deduction',
    operatingHours: '09:00 AM – 06:30 PM',
  },
  {
    id: 'rec-4',
    name: 'Swachh Bharat Metal & Plastic Aggregators',
    cpcbRegistrationNo: 'MPCB/RO-PUNE/CONSENT/55210',
    location: 'Katraj Bypass Scrap Market',
    city: 'Pune, Maharashtra',
    distanceKm: 3.1,
    reliabilityScore: 91,
    verified: true,
    phone: '+91 98902 67104',
    materialsAccepted: ['Long Cables', 'DishTV Parts', 'Rigid Plastics', 'Soft Toys (Textile recycling)'],
    pickupAvailable: true,
    minWeightKg: 15,
    specialOfferRate: 'Cash on spot or UPI transfer instantly',
    operatingHours: '07:30 AM – 09:00 PM',
  },
];

// Explicitly requested: replace sale history with TV, long cables, dishtv!
export const SALE_HISTORY: SaleHistoryItem[] = [
  {
    id: 'sale-001',
    lotId: 'KC-2026-00412',
    itemTitle: 'Sony Trinitron 21" CRT Television',
    category: 'tv',
    weightKg: 19.5,
    ratePerKg: 85,
    totalAmount: 1657,
    date: '10 Sep 2026',
    buyerName: 'EcoDismantle Authorized Hub',
    buyerCpcb: 'CPCB/EW-REG/MH/2023/0412',
    paymentMethod: 'UPI',
    paymentStatus: 'Paid',
    handoverCode: 'KC-HO-9941',
    materialPurity: 'Copper Deflection Coils & Chassis Intact',
    recoveredResources: '1.4 kg Copper, 4.2 kg Iron, 12 kg Lead-Silicate Glass',
  },
  {
    id: 'sale-002',
    lotId: 'KC-2026-00398',
    itemTitle: 'Heavy Armored Industrial Long Cables (Grade-1)',
    category: 'cables',
    weightKg: 38.0,
    ratePerKg: 520,
    totalAmount: 19760,
    date: '06 Sep 2026',
    buyerName: 'GreenTech Circular Refineries Pvt Ltd',
    buyerCpcb: 'CPCB/EW-REG/MH/2024/0981',
    paymentMethod: 'Cash',
    paymentStatus: 'Paid',
    handoverCode: 'KC-HO-9812',
    materialPurity: '98.5% Pure Bright Bare Copper Core',
    recoveredResources: '36.8 kg Electrolytic Grade Copper Wire, 1.2 kg PVC Insulation',
  },
  {
    id: 'sale-003',
    lotId: 'KC-2026-00365',
    itemTitle: 'DishTV Satellite Dish Antennas & Coaxial Cables',
    category: 'dishtv',
    weightKg: 14.2,
    ratePerKg: 62,
    totalAmount: 880,
    date: '28 Aug 2026',
    buyerName: 'Swachh Bharat Metal & Plastic Aggregators',
    buyerCpcb: 'MPCB/RO-PUNE/CONSENT/55210',
    paymentMethod: 'UPI',
    paymentStatus: 'Paid',
    handoverCode: 'KC-HO-9744',
    materialPurity: 'Galvanized Sheet Iron + Aluminum LNB feed horn',
    recoveredResources: '11.8 kg High-tensile Steel, 1.6 kg Cast Aluminum, 0.8 kg Brass',
  },
  {
    id: 'sale-004',
    lotId: 'KC-2026-00320',
    itemTitle: 'Mixed Desktop Computer Motherboards & Server Cards',
    category: 'pcb',
    weightKg: 12.0,
    ratePerKg: 185,
    totalAmount: 2220,
    date: '19 Aug 2026',
    buyerName: 'E-Parisaraa Precious Recovery Facility',
    buyerCpcb: 'CPCB/EW-REG/KA/2021/0088',
    paymentMethod: 'UPI',
    paymentStatus: 'Paid',
    handoverCode: 'KC-HO-9610',
    materialPurity: 'Dual Gold-Finger Memory Banks & Copper Traces',
    recoveredResources: '3.2g Gold, 18g Silver, 2.1kg Copper Cathode',
  },
];

// Explicitly requested: replace repair history with old phone, etc.!
export const REPAIR_HISTORY: RepairHistoryItem[] = [
  {
    id: 'rep-001',
    deviceName: 'Old Phone — Samsung Galaxy A20 (AMOLED Revive)',
    category: 'Mobile Smartphone',
    issueDiagnosed: 'Broken display touch glass + swollen battery cell (board 100% operational)',
    scrapEstimatedValue: 400,
    refurbishedMarketValue: 2400,
    netValueSaved: 2000,
    repairFacility: 'FixIt Circular Refurbishers (Kothrud)',
    date: '08 Sep 2026',
    status: 'Refurbished & Re-sold',
    daysTurnaround: 2,
    warrantyProvided: '6 Months Certified Refurbished Warranty',
  },
  {
    id: 'rep-002',
    deviceName: 'Old Phone — Redmi Note 8 (64GB Quad-Cam)',
    category: 'Mobile Smartphone',
    issueDiagnosed: 'Loose Type-C charging port solder joint + firmware bootloop',
    scrapEstimatedValue: 350,
    refurbishedMarketValue: 2100,
    netValueSaved: 1750,
    repairFacility: 'Digital Seva Refurbish Lab',
    date: '01 Sep 2026',
    status: 'Refurbished & Re-sold',
    daysTurnaround: 1,
    warrantyProvided: '90 Days Performance Guarantee',
  },
  {
    id: 'rep-003',
    deviceName: 'Old Phone — Realme C11 (Entry-Level 5000mAh)',
    category: 'Mobile Smartphone',
    issueDiagnosed: 'Cracked outer polarizer film & dirty audio receiver mesh',
    scrapEstimatedValue: 300,
    refurbishedMarketValue: 1800,
    netValueSaved: 1500,
    repairFacility: 'Swachh Gadget Refurbish Alliance',
    date: '22 Aug 2026',
    status: 'Repaired & Returned',
    daysTurnaround: 3,
    warrantyProvided: 'Standard Service Stamp',
  },
  {
    id: 'rep-004',
    deviceName: 'Heavy Mixer Grinder Induction Motor (Philips 750W)',
    category: 'Household Appliance',
    issueDiagnosed: 'Burned armature carbon brush and worn bronze sleeve bearing',
    scrapEstimatedValue: 150,
    refurbishedMarketValue: 950,
    netValueSaved: 800,
    repairFacility: 'KabaadSetu Verified Electrical Workshop',
    date: '14 Aug 2026',
    status: 'Repaired & Returned',
    daysTurnaround: 1,
    warrantyProvided: '1 Year Rewinding Warranty',
  },
];

// Explicitly requested: "CreateOwn" feature with DIY YouTube video tutorials for:
// - plastic bottles
// - damaged soft toys
// - wire and metal
// - dishtv and e-waste
export const CREATE_OWN_PROJECTS: DIYProject[] = [
  {
    id: 'diy-plastic-01',
    title: 'Self-Watering Sub-Irrigation Planters from 2L PET Bottles',
    titleHi: 'प्लास्टिक की बोतल से ऑटो-वाटरिंग प्लांटर बनाएं',
    titleMr: 'प्लास्टिकच्या बाटलीपासून स्वयंचलित झाडांचे कुंडे',
    materialType: 'plastic_bottles',
    materialLabel: 'Plastic Bottles',
    difficulty: 'Easy',
    timeEstimate: '20 mins',
    ecoPoints: 120,
    plasticDivertedGrams: 80,
    youtubeVideoId: 'wX24K577W4k',
    youtubeUrl: 'https://www.youtube.com/watch?v=wX24K577W4k',
    thumbnailUrl: 'https://images.unsplash.com/photo-1585320806297-9794b3e4eeae?w=600&auto=format&fit=crop&q=80',
    summary: 'Turn empty cold drink or water bottles into smart capillary hydroponic planters for herbs, mint, and flowers with zero wasted water.',
    materialsList: [
      '2x Clean 1.5L or 2L PET Soda Bottles',
      'Cotton rope or cloth strip (wicking fiber)',
      'Utility knife / Scissors',
      'Potting soil and seeds / seedling',
      'Water reservoir at bottom',
    ],
    steps: [
      {
        number: 1,
        title: 'Cut Bottle at 1/3 Upper Mark',
        description: 'Carefully cut the plastic bottle about 4 inches below the bottle cap neck using utility scissors.',
        timestampSec: 25,
      },
      {
        number: 2,
        title: 'Cap Perforation & Wick Insertion',
        description: 'Poke a 6mm hole in the bottle cap with a warm nail. Thread a 10-inch cotton cloth strip through the cap and tighten back.',
        timestampSec: 85,
      },
      {
        number: 3,
        title: 'Invert Top Funnel into Bottom Cup',
        description: 'Fill bottom base with 2 inches of clean water. Invert the top funnel downwards so the cotton wick submerges in water.',
        timestampSec: 140,
      },
      {
        number: 4,
        title: 'Fill with Soil and Plant',
        description: 'Pack loose soil around the wick and plant your seeds. The cotton wick draws moisture upward automatically for 2 weeks!',
        timestampSec: 210,
      },
    ],
    userLikes: 1420,
    completedCount: 684,
    featuredQuote: '“Saved 4 plastic bottles from landfill and now growing fresh coriander right on my balcony!”',
  },
  {
    id: 'diy-plastic-02',
    title: 'Vertical Hanging Garden Wall from Discarded 2L Bottles',
    titleHi: 'दीवार पर लटकने वाला वर्टिकल गार्डन टॉवर',
    titleMr: 'घराच्या भिंतीसाठी प्लास्टिक बाटल्यांचा वर्टिकल बगीचा',
    materialType: 'plastic_bottles',
    materialLabel: 'Plastic Bottles',
    difficulty: 'Intermediate',
    timeEstimate: '45 mins',
    ecoPoints: 240,
    plasticDivertedGrams: 350,
    youtubeVideoId: '2iP_yN_a59w',
    youtubeUrl: 'https://www.youtube.com/watch?v=2iP_yN_a59w',
    thumbnailUrl: 'https://images.unsplash.com/photo-1592417817098-8f3d6eb22513?w=600&auto=format&fit=crop&q=80',
    summary: 'Construct an eco-friendly modular vertical garden grid against boundary walls using interlocking plastic bottles and jute twine.',
    materialsList: [
      '6x Transparent 2L Plastic bottles',
      'Strong nylon cord or jute rope',
      'Drainage nail / soldering tip',
      'Compost and leaf mold mix',
      'Wall hooks or bamboo support',
    ],
    steps: [
      {
        number: 1,
        title: 'Cut Side Window Port',
        description: 'Cut an oval 3x6 inch opening in the side of each horizontal bottle while keeping structural edges rigid.',
        timestampSec: 30,
      },
      {
        number: 2,
        title: 'Punch Drainage & Suspension Holes',
        description: 'Punch 4 small holes at the bottom for runoff water, and 2 side holes for the hanging cord.',
        timestampSec: 90,
      },
      {
        number: 3,
        title: 'String Bottles in Cascading Tiers',
        description: 'Tie knots below each bottle to suspend them 8 inches apart. The overflow from the top tier hydrates the lower tier!',
        timestampSec: 180,
      },
    ],
    userLikes: 980,
    completedCount: 310,
    featuredQuote: '“Reduced outdoor heat on our tin shed roof and looks lush green!”',
  },
  {
    id: 'diy-toys-01',
    title: 'Cloud Floor Cushion & Pet Bed from Damaged Soft Toys',
    titleHi: 'फटे हुए टेडी बियर से शानदार कुशन और पालतू बिस्तर बनाएं',
    titleMr: 'खराब झालेल्या मऊ बाहुल्यांमधून मऊ उशी आणि बेड',
    materialType: 'soft_toys',
    materialLabel: 'Damaged Soft Toys',
    difficulty: 'Easy',
    timeEstimate: '30 mins',
    ecoPoints: 180,
    plasticDivertedGrams: 600,
    youtubeVideoId: 'kFwQ4X_H6bQ',
    youtubeUrl: 'https://www.youtube.com/watch?v=kFwQ4X_H6bQ',
    thumbnailUrl: 'https://images.unsplash.com/photo-1558060370-d644479cb6f7?w=600&auto=format&fit=crop&q=80',
    summary: 'Do not throw away stained or torn teddy bears! Their pure synthetic microfiber stuffing is ultra-resilient and creates hotel-grade floor poufs and dog beds.',
    materialsList: [
      '2-3 Torn or worn-out soft toys / plushies',
      'Old pillowcase or leftover bedsheet fabric',
      'Seam ripper or scissors',
      'Needle and heavy thread (or fabric glue)',
      'Eucalyptus or lavender drops for freshness',
    ],
    steps: [
      {
        number: 1,
        title: 'Extract Clean Fiber Filling',
        description: 'Open the back seam of the soft toys. Harvest the polyester polyfill cluster fluff and air it out under sunlight.',
        timestampSec: 20,
      },
      {
        number: 2,
        title: 'Card & Fluff the Fiber Bundles',
        description: 'Pull apart the compacted fibers by hand to restore maximum bounce and fluffiness.',
        timestampSec: 65,
      },
      {
        number: 3,
        title: 'Stuff Recycled Pillow Envelope',
        description: 'Tightly pack into an old cotton pillowcase, add 2 drops of essential oil, and hand-stitch the closure.',
        timestampSec: 130,
      },
      {
        number: 4,
        title: 'Enjoy Ergonomic Floor Seating',
        description: 'Provides orthopedic support for meditation, sitting work, or comfortable pet lounging.',
        timestampSec: 190,
      },
    ],
    userLikes: 2150,
    completedCount: 892,
    featuredQuote: '“Saved ₹1,200 on buying a pet cushion and gave our old childhood teddy a glorious second life.”',
  },
  {
    id: 'diy-toys-02',
    title: 'Draft Stopper & Acoustic Door Snake from Plush Pelts',
    titleHi: 'दरवाजे के नीचे की हवा रोकने वाला डिजाइनर ड्राफ्ट स्टॉपर',
    titleMr: 'दाराखालची हवा रोखण्यासाठी आकर्षक ड्राफ्ट स्टॉपर',
    materialType: 'soft_toys',
    materialLabel: 'Damaged Soft Toys',
    difficulty: 'Easy',
    timeEstimate: '25 mins',
    ecoPoints: 150,
    plasticDivertedGrams: 400,
    youtubeVideoId: '7U5ZJqD8XzE',
    youtubeUrl: 'https://www.youtube.com/watch?v=7U5ZJqD8XzE',
    thumbnailUrl: 'https://images.unsplash.com/photo-1563245372-f21724e3856d?w=600&auto=format&fit=crop&q=80',
    summary: 'Stitch together plush arms, legs, or long toy bodies into a dense thermal insulation snake that blocks AC cold leaks, dust, and insects under doors.',
    materialsList: [
      'Long plush toys (caterpillar, snake, or joined plush parts)',
      'Sand or pea-gravel pouch (weight ballast)',
      'Needle and thread',
    ],
    steps: [
      {
        number: 1,
        title: 'Measure Door Width',
        description: 'Measure the bottom gap of your bedroom or front door (typically 32 to 36 inches).',
        timestampSec: 15,
      },
      {
        number: 2,
        title: 'Link Plush Bodies in Series',
        description: 'Stitch heads and tails in a continuous cute cylinder. Insert a central sand pouch for grounding weight.',
        timestampSec: 75,
      },
      {
        number: 3,
        title: 'Slide Under Doorway',
        description: 'Reduces room noise by 35% and cuts monthly air conditioner power consumption.',
        timestampSec: 150,
      },
    ],
    userLikes: 870,
    completedCount: 425,
    featuredQuote: '“Blocks street dust completely and our room stays cooler for hours!”',
  },
  {
    id: 'diy-wire-01',
    title: 'Artisan Bonsai Tree Sculpture from Stripped Copper Cables',
    titleHi: 'तांबे के पुराने तारों से शानदार बोनसाई कलाकृति',
    titleMr: 'तांब्याच्या जुन्या तारांमधून सुंदर बोन्साय झाड शिल्प',
    materialType: 'wire_metal',
    materialLabel: 'Wire & Metal',
    difficulty: 'Creative Pro',
    timeEstimate: '60 mins',
    ecoPoints: 320,
    metalDivertedGrams: 450,
    youtubeVideoId: 'Xk-h8oVq99o',
    youtubeUrl: 'https://www.youtube.com/watch?v=Xk-h8oVq99o',
    thumbnailUrl: 'https://images.unsplash.com/photo-1579783902614-a3fb3927b675?w=600&auto=format&fit=crop&q=80',
    summary: 'Transform heavy gauge discarded copper cable strands into an exquisite, metallic Japanese bonsai centerpiece that sells for ₹2,000+ at art handicraft stalls!',
    materialsList: [
      '15-20 meters of stripped electrical copper wire',
      'Pliers and wire cutters',
      'Decorative rock or polished wooden slice base',
      'Clear protective lacquer spray (prevents patina tarnish)',
    ],
    steps: [
      {
        number: 1,
        title: 'Strip Wire Core Bundles',
        description: 'Carefully strip off PVC rubber insulation to expose the glossy rose-gold copper strands.',
        timestampSec: 35,
      },
      {
        number: 2,
        title: 'Twist Central Trunk Core',
        description: 'Gather 40 strands together and tightly twist the bottom 4 inches to form a gnarled, realistic tree trunk.',
        timestampSec: 110,
      },
      {
        number: 3,
        title: 'Branch & Foliage Splitting',
        description: 'Divide the upper strands into 5 primary canopy branches. Spiral smaller bunches into miniature leafy loops.',
        timestampSec: 220,
      },
      {
        number: 4,
        title: 'Anchor to Stone Base',
        description: 'Wrap root strands around a river stone or driftwood chunk. Spray with clear gloss to keep the copper shining forever!',
        timestampSec: 310,
      },
    ],
    userLikes: 3410,
    completedCount: 1120,
    featuredQuote: '“Made this from leftover house wiring. A buyer at Pune flea market paid ₹2,500 for it!”',
  },
  {
    id: 'diy-wire-02',
    title: 'Heavy-Duty Industrial Wire Storage Basket & Planter Cage',
    titleHi: 'मजबूत केबल और धातु के तारों से स्टोरेज बास्केट',
    titleMr: 'धातूच्या तारांपासून मजबूत स्टोरेज टोपली',
    materialType: 'wire_metal',
    materialLabel: 'Wire & Metal',
    difficulty: 'Intermediate',
    timeEstimate: '40 mins',
    ecoPoints: 220,
    metalDivertedGrams: 800,
    youtubeVideoId: '3k_vL1kF_1Y',
    youtubeUrl: 'https://www.youtube.com/watch?v=3k_vL1kF_1Y',
    thumbnailUrl: 'https://images.unsplash.com/photo-1544816155-12df9643f363?w=600&auto=format&fit=crop&q=80',
    summary: 'Weave stiff copper or galvanized wire scrap into geometric mesh organizers, fruit holders, or suspended planter baskets with Scandinavian industrial flair.',
    materialsList: [
      'Scrap galvanized binding wire / thick insulated wire',
      'Round bucket / cylinder as bending mold',
      'Wire twister tool or needle-nose pliers',
    ],
    steps: [
      {
        number: 1,
        title: 'Shape Structural Hoops',
        description: 'Bend two thick wire loops around a 10-inch bucket to create the top rim and bottom stabilizing base.',
        timestampSec: 20,
      },
      {
        number: 2,
        title: 'Weave Vertical Ribs',
        description: 'Cut 12 equal wire spokes and crimp them securely between top and bottom rims.',
        timestampSec: 80,
      },
      {
        number: 3,
        title: 'Lattice Intertwining',
        description: 'Spiral thin wire horizontally around the ribs for a rigid geometric diamond weave.',
        timestampSec: 160,
      },
    ],
    userLikes: 1190,
    completedCount: 512,
    featuredQuote: '“Sturdier than cheap store-bought plastic baskets and cost literally zero rupees.”',
  },
  {
    id: 'diy-dish-01',
    title: 'Repurposing DishTV Antenna into High-Efficiency Solar Cooker / Birdbath',
    titleHi: 'पुराने डिश टीवी एंटीना से सोलर कुकर व पक्षी जलकुंड',
    titleMr: 'जुन्या डिश टीव्ही अँटेनापासून सोलर कुकर आणि पक्षांसाठी पाण्याचे भांडे',
    materialType: 'dishtv_ewaste',
    materialLabel: 'DishTV & E-Waste',
    difficulty: 'Creative Pro',
    timeEstimate: '75 mins',
    ecoPoints: 450,
    metalDivertedGrams: 3500,
    youtubeVideoId: 'O8E6yq4l3-k',
    youtubeUrl: 'https://www.youtube.com/watch?v=O8E6yq4l3-k',
    thumbnailUrl: 'https://images.unsplash.com/photo-1509391365360-2e959784a276?w=600&auto=format&fit=crop&q=80',
    summary: 'The precise parabolic curve of an old Tata Play / DishTV dish can focus direct solar rays into a focal point that boils water in 15 minutes, or flips into a rustic garden birdbath!',
    materialsList: [
      '1x Discarded DishTV Parabolic Reflector Dish with mount arm',
      'Reflective mirror vinyl sticker sheet OR Mosaic mirror tiles',
      'Black matte cast-iron cooking vessel',
      'Adjustable angle bracket',
    ],
    steps: [
      {
        number: 1,
        title: 'Clean and Smooth Dish Surface',
        description: 'Scrape off outdoor dust and wash with soap to ensure the parabolic curve is clean and smooth.',
        timestampSec: 30,
      },
      {
        number: 2,
        title: 'Apply Radial Mirror Strips',
        description: 'Apply reflective chrome vinyl strips or broken mirror mosaic wedges radiating outward from the dish center.',
        timestampSec: 120,
      },
      {
        number: 3,
        title: 'Mount Pot at the LNB Focal Point',
        description: 'Replace the original LNB signal horn on the arm with a small metal ring holder for your black kettle or pot.',
        timestampSec: 240,
      },
      {
        number: 4,
        title: 'Cook with Free Sun Energy!',
        description: 'Aim at the sun — the concentrated focal point reaches 180°C and boils water or cooks lentils with zero gas or electricity!',
        timestampSec: 320,
      },
    ],
    userLikes: 4120,
    completedCount: 780,
    featuredQuote: '“Boils tea water on sunny afternoons without burning a single drop of LPG gas!”',
  },
  {
    id: 'diy-ewaste-02',
    title: 'Ultra-Quiet USB Desk Cooler from Discarded PC Chassis Fans',
    titleHi: 'पुराने कंप्यूटर पंखे से पोर्टेबल यूएसबी टेबल फैन',
    titleMr: 'कॉम्प्युटरच्या जुन्या फॅनपासून यूएसबी टेबल फॅन',
    materialType: 'dishtv_ewaste',
    materialLabel: 'DishTV & E-Waste',
    difficulty: 'Easy',
    timeEstimate: '20 mins',
    ecoPoints: 160,
    youtubeVideoId: '3vY45c4T9jA',
    youtubeUrl: 'https://www.youtube.com/watch?v=3vY45c4T9jA',
    thumbnailUrl: 'https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=600&auto=format&fit=crop&q=80',
    summary: 'E-waste computers have high-durability brushless 12V DC fans. Solder with an old phone charging cable for whisper-quiet workstation breeze.',
    materialsList: [
      '12V DC Brushless Fan from scrap CPU/power supply',
      'Old cut USB-A or Type-C phone charging cable',
      'Electrical tape or heat-shrink tube',
      'Bent coat-hanger or card stand',
    ],
    steps: [
      {
        number: 1,
        title: 'Identify Fan Polarity Leads',
        description: 'Strip the fan Red wire (+5V/12V) and Black wire (Ground). Discard yellow/blue tachometer wires.',
        timestampSec: 25,
      },
      {
        number: 2,
        title: 'Solder to USB Cable',
        description: 'Connect to the red and black wires of your USB cable. Insulate with electrical tape.',
        timestampSec: 80,
      },
      {
        number: 3,
        title: 'Mount and Power via Laptop USB',
        description: 'Plug into any phone charger brick or laptop USB port for continuous silent airflow.',
        timestampSec: 140,
      },
    ],
    userLikes: 1650,
    completedCount: 940,
    featuredQuote: '“Silent as a whisper and kept my study desk cool throughout summer.”',
  },
];

export const INITIAL_CHAT_MESSAGES = [
  {
    id: 'msg-1',
    sender: 'bot' as const,
    text: 'Namaste! I am ScrapSense Agentic AI (कबाड़-मित्र). Show me any scrap material, old electronics, or waste. I will analyze its brand, dimensions, purity, weight, and predict fair market rates from trusted MCX & CPCB registries with zero middleman cuts!',
    timestamp: 'Just now',
    suggestedPrompts: [
      '🔍 Analyze this Sony CRT TV',
      '⚡ Check price for 35kg Copper Cables',
      '📱 Should I sell or repair this old Phone?',
      '📡 Check rate for DishTV antenna lot',
      '🎨 How to recraft plastic bottles in CreateOwn?',
    ],
  },
];

export const SAMPLE_ANALYSIS_PRESETS: Record<string, AgentAnalysisResult> = {
  tv: {
    detectedItem: 'Vintage Color CRT Television (21-Inch)',
    brand: 'Sony Trinitron Super Fine Pitch',
    model: 'KV-21LT1B Series Chassis',
    dimensions: '510 mm x 480 mm x 490 mm',
    estimatedWeightKg: 19.2,
    primaryMaterial: 'High-Purity Copper Deflection Yoke + Lead-Barium CRT Glass',
    purityGrade: 'Industrial Grade-A Demanufacturing Core',
    confidenceScore: 94.2,
    predictedPriceMin: 1550,
    predictedPriceMax: 1750,
    decisionRecommendation: 'sell_recycle',
    decisionRationale: 'Cathode Ray Tubes carry vacuum implosion hazard and leaded glass toxicity. Must not be broken manually. Handover to CPCB authorized recycler for safe glass recovery and copper extraction.',
    marketSourcesCited: ['CPCB National E-Waste Register 2026', 'Maharashtra Metal Spot Exchange', 'MCX Industrial Secondary Scrap'],
    model3DType: 'tv',
    keyComponentsFound: ['1.35kg Heavy Copper Deflection Coil', 'Ferrite Flyback Transformer', 'Galvanized Shield Chassis', 'Heavy CRT Phosphor Glass'],
  },
  cables: {
    detectedItem: 'Heavy Armored Multicore Copper Power Cable Coil',
    brand: 'Polycab / Havells Grade-1 Spec',
    model: '4-Core 16 sq mm PVC Insulated Copper Armored',
    dimensions: '18 mm cable outer dia, 25-meter coil length',
    estimatedWeightKg: 38.5,
    primaryMaterial: 'Electrolytic Tough Pitch (ETP) Copper (99.2% Cu)',
    purityGrade: 'Grade-1 Bright Bare Wire (Zero Brass/Iron adulteration)',
    confidenceScore: 97.8,
    predictedPriceMin: 19200,
    predictedPriceMax: 20400,
    decisionRecommendation: 'sell_recycle',
    decisionRationale: 'Extremely high market value. Do NOT burn open insulation (illegal under Air Act). Authorized recyclers use mechanical wire strippers and pay +₹15/kg premium.',
    marketSourcesCited: ['MCX London Metal Exchange (LME) Spot Copper', 'Pune Hadapsar Wholesale Metal Mandi'],
    model3DType: 'cables',
    keyComponentsFound: ['Multi-strand ETP Pure Copper', 'Galvanized Steel Armor Wire', 'Extruded Lead-Free PVC Sheath'],
  },
  dishtv: {
    detectedItem: 'DTH Parabolic Satellite Dish Antenna + Receiver',
    brand: 'DishTV / Tata Play Digital Spec',
    model: 'Ku-Band 60cm Offset Elliptical Reflector',
    dimensions: '650 mm x 600 mm x 120 mm dish rim',
    estimatedWeightKg: 14.5,
    primaryMaterial: 'Cold Rolled Deep Draw Galvanized Steel + Aluminum Feed Horn',
    purityGrade: 'Structural Ferrous & Non-Ferrous Mixed Lot',
    confidenceScore: 91.5,
    predictedPriceMin: 800,
    predictedPriceMax: 920,
    decisionRecommendation: 'create_own_diy',
    decisionRationale: 'Can be sold for scrap (₹850), BUT can also be upcycled into a high-temperature Solar Sun Cooker or Garden Birdbath via CreateOwn, generating ₹2,000+ utility value!',
    marketSourcesCited: ['National Scrap Steel Aggregators', 'Maharashtra Sheet Metal Index'],
    model3DType: 'dishtv',
    keyComponentsFound: ['Galvanized Sheet Iron Parabolic Shell', 'Cast Aluminum LNB Mount Bracket', 'Coaxial Copper Clad Steel Lead'],
  },
  phone: {
    detectedItem: 'Android 4G Smartphone (AMOLED Display Core)',
    brand: 'Samsung Galaxy A-Series',
    model: 'SM-A205F (Dual SIM, 32GB Storage)',
    dimensions: '158.4 mm x 74.7 mm x 7.8 mm',
    estimatedWeightKg: 0.18,
    primaryMaterial: 'Monolithic Motherboard + Cobalt Lithium-Ion Battery + AMOLED',
    purityGrade: 'High-Salvage Electronic Subassembly',
    confidenceScore: 96.0,
    predictedPriceMin: 350,
    predictedPriceMax: 2400,
    decisionRecommendation: 'direct_repair',
    decisionRationale: '⭐ HIGH REFURBISH VALUE: Raw scrap value is only ₹350, but motherboard and camera sensors are 100% healthy. Refurbishing display & battery yields ₹2,100 to ₹2,400! Direct profit: +₹1,800 without middleman.',
    marketSourcesCited: ['All-India Mobile Refurbish Exchange', 'Gadget Salvage Index Pune', 'Urban E-Waste Precious Recovery'],
    model3DType: 'phone',
    keyComponentsFound: ['Exynos Mainboard (Gold Contact Pins)', '4000mAh Lithium-Cobalt Cell', 'Triple Sensor Camera Module', 'Glass Backing'],
  },
  pcb: {
    detectedItem: 'Enterprise Server Motherboards & High-Grade Computer PCBs',
    brand: 'Dell / HP Enterprise Green Board Class',
    model: 'Multi-Socket Server Board + DDR4 RAM array',
    dimensions: '305 mm x 244 mm ATX Standard',
    estimatedWeightKg: 12.0,
    primaryMaterial: 'High-Density Multilayer FR-4 with Gold Finger Connectors',
    purityGrade: 'Class-A Precious Metal High Recovery',
    confidenceScore: 95.3,
    predictedPriceMin: 2100,
    predictedPriceMax: 2350,
    decisionRecommendation: 'sell_recycle',
    decisionRationale: 'High concentrations of Gold (3g/ton eq.), Silver, and Palladium. Authorized smelters use hydrometallurgical refining with zero acid dump pollution.',
    marketSourcesCited: ['CPCB Precious Metal E-Waste Guideline', 'Bangalore Urban Mining Exchange'],
    model3DType: 'pcb',
    keyComponentsFound: ['Electrolytic Gold Plated Pins', 'High-Copper Ground Planes', 'Tantalum Capacitors', 'BGA Microprocessor Sockets'],
  },
};
